services:
  proof-server:
    image: "midnightnetwork/proof-server:4.0.0"
    container_name: 'midnight-proof-server'
    command: ["midnight-proof-server --network undeployed"]
    ports:
      - "6300:6300"
    environment:
      RUST_BACKTRACE: "full"